// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'my_structure';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String ONBOARD1 = 'assets/onboard/onboard1.png';
  static const String ONBOARD2 = 'assets/onboard/onboard2.png';
  static const String ONBOARD3 = 'assets/onboard/onboard3.png';
}
